#!/usr/bin/env python

import subprocess

cmds = ["find", "wavesim", "(", "-name", "*.c", "-or", "-name", "*.h", ")", "-exec", "grep", "-H", "return WS_", "{}", ";"]
wrong_returns = subprocess.check_output(cmds).decode('utf-8').strip().split('\n')
print("Suggest using 'WSRET(WS_...)' instead of 'return WS_...'")
print("  " + "\n   ".join(wrong_returns))
